# Site settings
title: La Poterie Du Vexin
email: lapoterieduvexin@hotmail.fr
url: poterie-vexin.fr
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
#  primary-dark: '#000000'
#  links: '#219ab3'

  primary-dark: '#FFFFFF'
  links: '#555555'

# Footer settings
footer: La Poterie du Vexin

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://fr-fr.facebook.com/lapoterieduvexin

# Build settings
markdown: kramdown
permalink: pretty
